name: Generate Doxygen Site and Push to Web Branch

on:
  push:
    branches:
      - main

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Main Branch
        run: git pull origin main

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Clean Web Branch
        run: |
          git fetch origin
          git checkout -b web origin/web || git checkout -b web

      - name: Generate Doxygen Site
        run: |
          cd docs
          doxygen Doxyfile

      - name: Copy HTML Files to Web Branch
        run: |
          mkdir -p ../temp_web_branch
          cp -r docs/html/* ../temp_web_branch
          rm -rf docs/html
          mv ../temp_web_branch/* .
          rm -rf ../temp_web_branch

      - name: Commit and Push to Web Branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Move Doxygen HTML files to web branch root"
          git push origin web
