name: Generate Doxygen Site and Push to Web Branch

on:
  push:
    branches:
      - main

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Main Branch
        run: git pull origin main

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Clean Web Branch
        run: |
          git branch web main
          git checkout -b web origin/web || git checkout -b web

      - name: Generate Doxygen Site
        run: |
          cd docs
          doxygen Doxyfile

      - name: Commit and Push to Web Branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Generate Doxygen site"
          git push origin web
