name: Generate Doxygen Site and Push to Web Branch

on:
  push:
    branches:
      - main

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate Doxygen Site
        run: |
          cd docs
          doxygen Doxyfile

      - name: Commit and Push to Web Branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b web
          git add .
          git commit -m "Generate Doxygen site"
          git push origin web
