name: Build and Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Doxygen
      run: sudo apt-get install -y doxygen

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Documentation
      run: |
        cd docs
        doxygen Doxyfile
        cd ..

    - name: Copy Docs to Web Branch
      run: |
        mkdir -p ../web
        cp -r docs/html/* ../web/

    - name: Configure Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Update Web Branch
      run: |
        git remote add web-remote "${{ github.repository }}"
        git fetch web-remote web
        git checkout web
        find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -r {} +
        cp -r ../web/* .
        git add .
        git commit -m "Update web branch with documentation"
        git push web-remote web
