name: Build and Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    - name: Set working directry
      run: mkdir work && cd work

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Doxygen
      run: sudo apt-get install -y doxygen

    - name: Build Documentation
      run: |
        cd docs
        doxygen Doxyfile
        cd ..

    - name: Copy Docs to Web Branch
      run: |
        mkdir -p ../web
        cp -r docs/html/* ../web/
        
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        
        git pull origin web
        find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -r {} +
        cp -r ../web/*
        git commit -m "Update web branch with documentation"
        git push origin web
