name: Build and Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set working directry
      run: mkdir work && cd work
      
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Doxygen
      uses: mattnotmitt/doxygen-action@edge
      with:
          working-directory: 'docs/'
          doxyfile-path: 'docs/doxygen/'

    - name: Copy Docs to Web Branch
      run: |
        mkdir -p ../web
        cp -r docs/html/* ../web/
        git config pull.rebase false
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        
        git pull --rebase origin web
        find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -r {} +
        cp -r ../web/* .
        git add .
        git commit -m "Update web branch with documentation"
        git push origin HEAD:web
