name: Doxygen

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apt-get install doxygen

    - name: Generate Doxygen Documentation
      run: |
        cd docs
        doxygen Doxyfile

    - name: Copy HTML to web branch
      run: |
        mkdir web
        cp -r docs/html/* web/

    - name: Push to web branch
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout -b web
        git add -A
        git commit -m "Update HTML documentation"
        git push origin web
