name: Generate and Deploy Doxygen Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-doxygen:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Doxygen
      run: sudo apt-get install -y doxygen

    - name: Generate Doxygen documentation
      run: cd docs && doxygen Doxyfile && cd ..

  deploy-to-web-branch:
    runs-on: ubuntu-latest
    needs: generate-doxygen
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy Doxygen HTML to web branch
      run: |
        cp -r docs/html/. web/
        git add web
        git commit -m "Update Doxygen documentation"
        git push

